# Personal Information
name = "keyteo_-_mohamed_bennekrouf_v27_en"
phonenumber = ""
email = ""
address = ""
picture = "profile.png"

# Job title
job_title = "Technical Lead"

# Manager information
manager_name = "Anthony Levavasseur"
manager_email = "alevavasseur@keyteo.ch"
manager_phone = "078 230 36 38"

# Consultant information  
consultant_name = "keyteo_-_mohamed_bennekrouf_v27_en"

# Manager information
manager_info = "Anthony Levavasseur – alevavasseur@keyteo.ch – 078 230 36 38"

company_logo = "logo.png"
company_name = ""

[links]
github = ""
linkedin = ""
personal = ""

# Technical Skills
[skills]
Languages = [""]
Frameworks = [""]
Others = [""]

# Education & Certifications
[[education]]
title = ""
date = ""

# Languages
[languages]
native = [""]
fluent = [""]
intermediate = [""]
basic = [""]
